<?php

declare(strict_types=1);

use App\Models\NativeCommand;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        NativeCommand::updateOrCreate(['slug' => 'neon-discord-execution'], [
            'slug' => 'neon-discord-execution',
            'description' => 'Executes Discord commands generated by Neon AI.',
            'class' => \App\Jobs\NativeCommand\ProcessNeonDiscordExecutionJob::class,
            'usage' => 'Usage: Internal command processor',
            'example' => 'Example: Internal use only',
            'is_active' => false,
        ]);
    }

    public function down(): void
    {
        NativeCommand::where('slug', 'neon-discord-execution')->delete();
    }
};
