<?php

declare(strict_types=1);

use App\Models\NativeCommand;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        NativeCommand::updateOrCreate(['slug' => 'neon-sql-execution'], [
            'slug' => 'neon-sql-execution',
            'description' => 'Executes SQL commands generated by Neon AI.',
            'class' => \App\Jobs\NativeCommand\ProcessNeonSQLExecutionJob::class,
            'usage' => 'Usage: Internal command processor',
            'example' => 'Example: Internal use only',
            'is_active' => false,
        ]);
    }

    public function down(): void
    {
        NativeCommand::where('slug', 'neon-sql-execution')->delete();
    }
};
