<?php

use App\Models\User;
use Spark\Features;

return [

    /*
    |--------------------------------------------------------------------------
    | Spark Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URI at which the Spark billing
    | portal is available. You are free to change this URI to a value that
    | you prefer. You shall link to this location from your application.
    |
    */

    'path' => 'billing',

    /*
    |--------------------------------------------------------------------------
    | Spark Middleware
    |--------------------------------------------------------------------------
    |
    | These are the middleware that requests to the Spark billing portal must
    | pass through before being accepted. Typically, the default list that
    | is defined below should be suitable for most Laravel applications.
    |
    */

    'middleware' => ['web', 'auth'],

    /*
    |--------------------------------------------------------------------------
    | Branding
    |--------------------------------------------------------------------------
    |
    | These configuration values allow you to customize the branding of the
    | billing portal, including the primary color and the logo that will
    | be displayed within the billing portal. This logo value must be
    | the absolute path to an SVG logo within the local filesystem.
    |
    */

    'brand' => [
        'logo' => resource_path('/img/neon.svg'),
        'color' => 'bg-pink-600',
    ],

    /*
    |--------------------------------------------------------------------------
    | Proration Behavior
    |--------------------------------------------------------------------------
    |
    | This value determines if charges are prorated when making adjustments
    | to a plan such as incrementing or decrementing the quantity of the
    | plan. This also determines proration behavior if changing plans.
    |
    */

    'prorates' => true,

    /*
    |--------------------------------------------------------------------------
    | Spark Date Format
    |--------------------------------------------------------------------------
    |
    | This date format will be utilized by Spark to format dates in various
    | locations within the billing portal, such as while showing invoice
    | dates. You should customize the format based on your own locale.
    |
    */

    'date_format' => 'F j, Y',

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Spark's features are optional. You may disable the features by
    | removing them from this array. By removing features from this array
    | you can customize your Spark experience for your own application.
    |
    */

    'features' => [
        // Features::billingAddressCollection(['required' => true]),
        // Features::mustAcceptTerms(),
        // Features::euVatCollection(['home-country' => 'BE']),
        Features::invoiceEmails(['custom-addresses' => true]),
        Features::paymentNotificationEmails(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Invoice Configuration
    |--------------------------------------------------------------------------
    |
    | The following configuration options allow you to configure the data that
    | appears in PDF invoices generated by Spark. Typically, this data will
    | include a company name as well as your company contact information.
    |
    */

    'invoice_data' => [
        'vendor' => 'Metacomet Technologies, LLC',
        'product' => 'Neon Bot Subscription',
        'street' => '2389 Main St., Suite 100',
        'location' => 'Glastonbury, CT 06033',
    ],

    /*
    |--------------------------------------------------------------------------
    | Spark Billable
    |--------------------------------------------------------------------------
    |
    | Below you may define billable entities supported by your Spark driven
    | application. The Stripe edition of Spark currently only supports a
    | single billable model entity (team, user, etc.) per application.
    |
    | In addition to defining your billable entity, you may also define its
    | plans and the plan's features, including a short description of it
    | as well as a "bullet point" listing of its distinctive features.
    |
    */

    'billables' => [

        'neon' => [
            'model' => User::class,

            // Use this option if the trial doesn't require a credit card up front
            // 'trial_days' => 10,

            'default_interval' => 'yearly',

            'plans' => [
                [
                    'name' => 'Neon Basic',
                    'short_description' => 'Basic plan for Neon',
                    'monthly_id' => 'price_1QteVZHSbCCl70iIoppjlXqM',
                    'yearly_id' => 'price_1QteafHSbCCl70iIpsLIMILg',
                    'yearly_incentive' => '1 Month Free!',
                    // Use this option if the trial requires a credit card up front
                    // 'trial_days' => 30,
                    'features' => [
                        'Send Welcome Messages',
                        '1 Live Stream Notification (Twitch only)',
                        '4 Custom Commands',
                        '-- AI Commands',
                        '-- Unlimited Custom Commands',
                    ],
                ],
                [
                    'name' => 'Neon Premium',
                    'short_description' => 'Premium plan for Neon',
                    'monthly_id' => 'price_1QterDHSbCCl70iIyXOVbdor',
                    'yearly_id' => 'price_1QtfAlHSbCCl70iIreWQP8L8',
                    'yearly_incentive' => '1 Month Free!',
                    // Use this option if the trial requires a credit card up front
                    // 'trial_days' => 30,
                    'features' => [
                        'Everything in Basic +',
                        'Live Stream Notifications',
                        'Unlimited Custom Commands',
                        'AI Commands',
                    ],
                ],
            ],

        ],
    ],
];
