name: Build and Deploy Assets

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up PHP and install Composer dependencies
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'  # adjust to your PHP version

      - name: Configure Composer for Nova Private Repository
        run: composer config http-basic.nova.laravel.com "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_LICENSE_KEY }}"

      - name: Configure Composer for Spark Private Repository
        run: composer config http-basic.spark.laravel.com "${{ secrets.SPARK_USERNAME }}" "${{ secrets.SPARK_LICENSE_KEY }}"

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # 3. Set up Node.js and install front-end dependencies
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # or your desired Node version

      - name: Install dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build

      - name: Configure AWS CLI for DigitalOcean Spaces
        run: |
          aws configure set aws_access_key_id ${{ secrets.DO_SPACES_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.DO_SPACES_SECRET }}
          aws configure set default.region us-east-1  # Dummy region; not used by DO Spaces
        env:
          DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
          DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}

      - name: Sync assets to DigitalOcean Spaces
        run: |
          aws s3 sync ./public/build s3://${{ vars.DO_SPACES_BUCKET }}/public/build \
            --endpoint-url https://${{ vars.DO_SPACES_ENDPOINT }} \
            --acl public-read

      - name: Trigger Envoyer deployment
        run: curl -X POST https://envoyer.io/deploy/${{ secrets.ENVOYER_CODE }}
